name: medicine_reminder
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  android_alarm_manager_plus: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0



# The following section is specific to Flutter packages.
flutter:

 
  # the material Icons class.
  uses-material-design: true

  
